---
- name: preparing management node local
  hosts: 127.0.0.1
  roles:
        - common

- name: Installing Nginx + PHP-FPM
  hosts: kipling-web01
  roles:
        - common
        - nginx
        - php-fpm

#- name: Installing MySQL
#  hosts: kipling-mysql01
#  roles:
#        - common
#        - mysql    
