---
- name: preparing management node local
  hosts: 127.0.0.1
  roles:
        - common

- name: Installing Nginx + PHP-FPM
  hosts: web02
  roles:
        - common
        - nginx
        - php-fpm
        - magento-app

- name: Installing MySQL
  hosts: kipling-mysql01
  roles:
        - common
        - mysql
        - magento-db 
