---

- name: Create document root for Magento
  file: path={{ vhost_document_root }} state=directory owner={{ magento_user }} group={{ magento_user }}  mode=0775
  ignore_errors: yes

- name: Configure and Restart Nginx
  template: src=magento.conf.j2 dest=/etc/nginx/conf.d/magento.conf
  notify: restart nginx


