---

- name: Create document root for Magento
  file: path={{ vhost_document_root }} state=directory owner={{ magento_user }} group={{ magento_user }}  mode=0775
  ignore_errors: yes
  when: 
        create_document_root == True

- name: Configure and Restart Nginx
  template: src=magento.conf.j2 dest=/etc/nginx/conf.d/magento.conf
  notify: restart nginx

- name: generate install_magento.sh
  template: src=install_magento.sh.j2 dest={{ vhost_document_root  }}/install_magento.sh mode=0755
  when: 
        install_magento == True
  notify: install magento



